### ISSUE TITLE
Wrong bip39 function called to create seed array from word list

### ISSUE THREAD

**Issue by TRtomasz** [casper-ecosystem/casper-client-sdk#418] opened 2024-04-16 08:25 UTC
**Describe the bug**
i Couldnt understand why i cant get same keys using casper js-sdk as when using casper-wallet i think issue is here  https://github.com/casper-ecosystem/casper-js-sdk/blob/dev/src/lib/CasperHDKeys/CasperHDKey.ts#L57 casper-js-sdk calls `bip39.mnemonicToEntropy`
While casper-wallet calls `bip39.mnemonicToSeedSync` 
https://github.com/make-software/casper-wallet/blob/develop/src/libs/crypto/bip39.ts#L11

**To Reproduce**

Identify if any Prequisites:

2.  ..

**Expected behavior**

**Screenshots**

**Additional context**

**Defect Type**
- [ ] Regression
- [ ] New
- [ ] Escape

**Comment by ryoknz** [comment] 2024-04-16 08:26
Duplicate of https://github.com/casper-ecosystem/casper-js-sdk/issues/410
Please check https://github.com/casper-ecosystem/casper-js-sdk/pull/413

**Closed as not planned by ryoknz** 2024-04-16 08:26 UTC
Labels: bug, duplicate
