### ISSUE TITLE
warning message from typedjson

### ISSUE THREAD

**Issue by flipscholtz** [casper-ecosystem/casper-client-sdk#310] opened 2023-06-07 08:24 UTC
# Description
casper-js-sdk version 2.13.0 and 2.13.1 causes the following message to be logged from the typedjson library on startup and when running tests.

```
@jsonMember on e.StoredValue: cannot resolve specified property constructor at runtime. If the type is not yet defined, for example due to circular references, add '() => ' before it. E.g. @jsonMember(() => Foo)
```

This does not happen with version 2.12.1.

Environment:
AWS lambda, Node v19.4.0

# Proposed fix
I tried changing the decorator on EraSummary.StoredValue [here](https://github.com/casper-ecosystem/casper-js-sdk/blob/5a15da0e31981006a5e00ecc943453eb2cf8ab3a/src/services/CasperServiceByJsonRPC.ts#LL235C1-L235C1) , from this:
```
 @jsonMember({ constructor: StoredValue, name: 'stored_value' })
```
to this:
```
  @jsonMember(() => ({ constructor: StoredValue, name: 'stored_value' }))
```
and the warning no longer appears.

**Comment by gyroflaw** [comment] 2023-06-14 05:38
duplicate of https://github.com/casper-ecosystem/casper-js-sdk/issues/76

**Closed as not planned by gyroflaw** 2023-06-14 05:38 UTC
Labels: bug, duplicate
