### ISSUE TITLE
AccountHash support

### ISSUE THREAD

**Issue by KillianH** [casper-ecosystem/casper-client-sdk#224] opened 2023-01-10 06:27 UTC
**Describe the bug**
AccountHash CLType isn't supported

https://github.com/casper-ecosystem/casper-js-sdk/blob/7da7c50/src/lib/CLValue/AccountHash.ts#L66

The Account Hash CLType is missing the toBytes() method. This is needed in order to support CasperLabs private auction smart contract.

Can you provide a way to insert an account hash with the sdk into a deploy ?

**Comment by RitaMAllenCA** [comment] 2023-01-17 21:35
@hoffmannjan please triage and add a comment so we can propose next steps, thank you

**Comment by RitaMAllenCA** [comment] 2023-01-21 00:43
@hoffmannjan I thought this had been released - no?

**Comment by hoffmannjan** [comment] 2023-01-23 15:51
nope, but we can release a new `minor` release with this :)

**Comment by hoffmannjan** [comment] 2023-01-23 15:56
@KillianH I checked and it's not a bug, if you look at the top of the file:

```
// NOTE: Currently this isn't supported CLValue
// Don't export it outside internal code!
```

But currently it changed so we can do this - will be in next released scheduled for the end of this month. Cheers!

**Comment by KillianH** [comment] 2023-01-23 16:03
Thx !

**Comment by hoffmannjan** [comment] 2023-02-07 15:12
@KillianH could you test [feat/acc-hash](https://github.com/casper-ecosystem/casper-js-sdk/pull/236) - and confirm it works as expected for you?

**Closed as completed** 2023-02-09 15:27 UTC
