### ISSUE TITLE
Two approvals when signing a Transaction object

### ISSUE THREAD

**Issue by KillianH** [casper-ecosystem/casper-client-sdk#465] opened 2024-12-16 21:21 UTC
**Describe the bug**
When signing a Transaction object and serializing it back to JSON I get two approvals instead of one.

https://github.com/casper-ecosystem/casper-js-sdk/blob/feat-5.0.0/src/types/Transaction.ts#L505

The code add a first approval to the transaction object and another one to the deploy or transactionV1 object.

**To Reproduce**

Identify if any Prequisites:

1. Use sign() or setSignature() from the Transaction Class

**Expected behavior**
Signing with a single key should add a single approval ?

**Screenshots**

**Additional context**

Add a test to verify the number of approvals
https://github.com/casper-ecosystem/casper-js-sdk/blob/feat-5.0.0/src/types/Transaction.test.ts#L85

**Defect Type**
- [x] Regression

**Comment by alexmyshchyshyn** [comment] 2024-12-20 17:01
Hey @KillianH . The issue is fixed in the latest version - `5.0.0-beta1`.

**Closed as completed by alexmyshchyshyn** 2024-12-20 17:01 UTC
Labels: bug
